# Generated by Django 4.2 on 2023-04-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=15)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.network'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection1', to='main.interface')),
                ('interface2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection2', to='main.interface')),
            ],
        ),
    ]
