# Generated by Django 4.2 on 2023-04-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_device_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('pc', 'PC')], default='router', max_length=10),
        ),
    ]
