# Generated by Django 4.2 on 2023-04-19 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='device1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='connections1', to='main.device'),
        ),
        migrations.AddField(
            model_name='connection',
            name='device2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='connections2', to='main.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='interfaces',
            field=models.ManyToManyField(blank=True, related_name='devices', to='main.interface'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='interface1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections1', to='main.interface'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='interface2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections2', to='main.interface'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('device1', 'interface1', 'device2', 'interface2')},
        ),
    ]
