# Generated by Django 4.2 on 2023-04-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_connection_unique_together_connection_device1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='device1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_device1', to='main.device'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='device2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_device2', to='main.device'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='interface1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_interface1', to='main.interface'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='interface2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_interface2', to='main.interface'),
        ),
    ]
