# Generated by Django 4.2 on 2023-04-19 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_connection_device1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='device1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections1', to='main.device'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='device2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections2', to='main.device'),
        ),
    ]
